import type { JourneyData } from "@/types/journey";

// Chronological helper shared by the phase-based sections (story, tech evolution).
function parsePeriodRange(period: string): { min: number; max: number } {
  const yearMatches = period.match(/\b(19|20)\d{2}\b/g);
  if (!yearMatches || yearMatches.length === 0) return { min: 0, max: 0 };
  const years = yearMatches.map((y) => parseInt(y, 10));
  return { min: Math.min(...years), max: Math.max(...years) };
}

function sortNewestFirst<T extends { period: string }>(phases: T[]): T[] {
  return [...phases].sort((a, b) => {
    const rangeA = parsePeriodRange(a.period);
    const rangeB = parsePeriodRange(b.period);
    return rangeB.min - rangeA.min || rangeB.max - rangeA.max;
  });
}

export function journeyToMarkdown(journey: JourneyData): string {
  const { github_data, ai_persona, ai_story, ai_tech_evolution, ai_skills, ai_career_projection } = journey;
  const { user } = github_data;
  const lines: string[] = [];

  lines.push(`# ${user.name || journey.github_username}'s Code Persona`);
  lines.push("");
  lines.push(`**@${journey.github_username}** · [github.com/${journey.github_username}](https://github.com/${journey.github_username})`);
  if (user.bio) lines.push(`\n${user.bio}`);
  lines.push("");
  lines.push(`- Public repos: ${github_data.repos?.length ?? user.public_repos}`);
  lines.push(`- Followers: ${user.followers}`);
  if (user.location) lines.push(`- Location: ${user.location}`);
  if (user.company) lines.push(`- Company: ${user.company}`);
  lines.push("");

  if (ai_persona) {
    lines.push("## Developer Profile");
    if (ai_persona.title) lines.push(`\n**${ai_persona.title}**`);
    if (ai_persona.codingStyle) lines.push(`\n${ai_persona.codingStyle}`);
    if (ai_persona.insights?.length) {
      lines.push("\n**Key Strengths:**");
      ai_persona.insights.forEach((insight) => lines.push(`- ${insight}`));
    }
    lines.push("");
  }

  if (ai_story?.phases?.length) {
    lines.push("## Career Timeline");
    lines.push("");
    sortNewestFirst(ai_story.phases).forEach((phase) => {
      lines.push(`### ${phase.period}: ${phase.title}`);
      lines.push(`\n${phase.description}`);
      if (phase.significance) lines.push(`\n_${phase.significance}_`);
      if (phase.keyRepos?.length) lines.push(`\nNotable projects: ${phase.keyRepos.join(", ")}`);
      lines.push("");
    });
  }

  if (ai_tech_evolution?.phases?.length) {
    lines.push("## Technical Expertise");
    lines.push("");
    sortNewestFirst(ai_tech_evolution.phases).forEach((phase) => {
      lines.push(`### ${phase.period}: ${phase.focus}`);
      if (phase.technologies?.length) lines.push(`\n${phase.technologies.join(", ")}`);
      if (phase.reasoning) lines.push(`\n${phase.reasoning}`);
      lines.push("");
    });
  }

  if (ai_skills?.skills?.length) {
    lines.push("## Core Competencies");
    lines.push("");
    ai_skills.skills.forEach((skill) => {
      lines.push(`- **${skill.name}** (${skill.score}/100)  \n  ${skill.reasoning}`);
    });
    lines.push("");
  }

  if (ai_career_projection) {
    lines.push("## Growth Trajectory");
    if (ai_career_projection.prediction) lines.push(`\n${ai_career_projection.prediction}`);
    if (ai_career_projection.roleAlignment) lines.push(`\n**Ideal role:** ${ai_career_projection.roleAlignment}`);
    if (ai_career_projection.futureSkills?.length) {
      lines.push(`\n**Growth areas:** ${ai_career_projection.futureSkills.join(", ")}`);
    }
    if (ai_career_projection.learningPath?.length) {
      lines.push("\n**Recommended path:**");
      ai_career_projection.learningPath.forEach((step, i) => lines.push(`${i + 1}. ${step}`));
    }
    lines.push("");
  }

  lines.push("---");
  lines.push(`_Generated by [Code Persona](https://codepersona.app) · codepersona.app/${journey.github_username}_`);

  return lines.join("\n");
}

export function downloadMarkdown(journey: JourneyData) {
  const markdown = journeyToMarkdown(journey);
  const blob = new Blob([markdown], { type: "text/markdown;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${journey.github_username}-codepersona.md`;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}
